baseURL = 'https://bytejournery.vercel.app/'
languageCode = 'en-us'
title = 'My Hugo Blog'
theme = 'PaperMod'

[params]
  ShowReadingTime = true

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Posts"
    url = "/posts"
    weight = 2
